// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $agendacsr_index from "./routes/agendacsr/index.tsx";
import * as $agendassr_index from "./routes/agendassr/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Addjobs from "./islands/Addjobs.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/agendacsr/index.tsx": $agendacsr_index,
    "./routes/agendassr/index.tsx": $agendassr_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Addjobs.tsx": $Addjobs,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
